var sitemap = 
{
"rootNodes":[
{
"pageName":"迎新",
"type":"Wireframe",
"url":"迎新.html",
"children":[
{
"pageName":"国有资产",
"type":"Wireframe",
"url":"国有资产.html",
"children":[
{
"pageName":"国有资产首页",
"type":"Wireframe",
"url":"国有资产首页.html"},
{
"pageName":"购买学生用品",
"type":"Wireframe",
"url":"购买学生用品.html"},
{
"pageName":"购买情况统计",
"type":"Wireframe",
"url":"购买情况统计.html"}]},
{
"pageName":"院系领导",
"type":"Wireframe",
"url":"院系领导.html",
"children":[
{
"pageName":"院系领导首页",
"type":"Wireframe",
"url":"院系领导首页.html"},
{
"pageName":"绿色通道审核",
"type":"Wireframe",
"url":"绿色通道审核.html"},
{
"pageName":"通过情况统计",
"type":"Wireframe",
"url":"通过情况统计.html"}]},
{
"pageName":"学校领导",
"type":"Wireframe",
"url":"学校领导.html",
"children":[
{
"pageName":"学院领导首页",
"type":"Wireframe",
"url":"学院领导首页.html"},
{
"pageName":"学生报道查询",
"type":"Wireframe",
"url":"学生报道查询.html"}]},
{
"pageName":"教务处",
"type":"Wireframe",
"url":"教务处.html",
"children":[
{
"pageName":"教务处首页",
"type":"Wireframe",
"url":"教务处首页.html"},
{
"pageName":"学籍注册",
"type":"Wireframe",
"url":"学籍注册.html"},
{
"pageName":"院系维护",
"type":"Wireframe",
"url":"院系维护.html"},
{
"pageName":"关于我们",
"type":"Wireframe",
"url":"关于我们.html"}]},
{
"pageName":"计财处",
"type":"Wireframe",
"url":"计财处.html",
"children":[
{
"pageName":"计财处首页",
"type":"Wireframe",
"url":"计财处首页.html"},
{
"pageName":"学生缴费情况",
"type":"Wireframe",
"url":"学生缴费情况.html"},
{
"pageName":"网上迎新情况",
"type":"Wireframe",
"url":"网上迎新情况.html"}]}]}]};
